import { useEffect, useState } from 'react'
import { Activity, ArrowRight, BookOpen, Check, CheckCheck, ChevronRight, Clock3, ExternalLink, FileClock, Inbox, Link2, Plus, RefreshCcw, RotateCcw, Search, Send, ShieldCheck, X } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { addAttempt, decideCase, findingFor, handoff, isCurrent, nextAttempt, openCase, refreshCase, runbookFor, scopedAttempts, seedState, type Attempt, type Case, type Finding, type State, type Ticket, uncertain } from '@/lib/workflow'

const key = 'casework-public-demo-v1'
function restored(): State { try { const s = JSON.parse(localStorage.getItem(key) || 'null'); if (s?.version === 1 && Array.isArray(s.cases) && Array.isArray(s.attempts) && Array.isArray(s.desk)) return s } catch { /* restore seed */ } return seedState() }
const time = (s: string) => new Date(s).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false, timeZone: 'UTC' }) + ' UTC'
const label: Record<Finding, string> = { NO_RECORD: 'No delivery record', ACKNOWLEDGED: 'Endpoint acknowledged', MULTIPLE_ACKS: 'Multiple acknowledgments', RETRY_SCHEDULED: 'Retry scheduled', RETRY_UNOBSERVED: 'Retry not observed', FAILED_UNRESOLVED: 'Unresolved failure' }
const color: Record<Finding, string> = { NO_RECORD: 'bg-amber-50 text-amber-800', ACKNOWLEDGED: 'bg-emerald-50 text-emerald-700', MULTIPLE_ACKS: 'bg-violet-50 text-violet-700', RETRY_SCHEDULED: 'bg-blue-50 text-blue-700', RETRY_UNOBSERVED: 'bg-amber-50 text-amber-800', FAILED_UNRESOLVED: 'bg-red-50 text-red-700' }
const status = { pending_review: 'Needs review', approved: 'Approved', rejected: 'Rejected', handed_off: 'Handed off' }
type View = 'queue' | 'delivery' | 'desk' | 'guide'
type Pane = 'evidence' | 'draft' | 'activity'

export default function App() {
  const [data, setData] = useState(restored)
  const [chosen, setChosen] = useState(() => data.cases.find(c => c.ticket_id === 'T-1042')?.id || '')
  const [view, setView] = useState<View>('queue')
  const [pane, setPane] = useState<Pane>('evidence')
  const [search, setSearch] = useState('')
  const [message, setMessage] = useState(() => data.cases.find(c => c.ticket_id === 'T-1042')?.draft || '')
  const [reviewer, setReviewer] = useState('Demo reviewer')
  const [ack, setAck] = useState(false)
  const [form, setForm] = useState<'case' | 'attempt' | null>(null)
  const [notice, setNotice] = useState<{ text: string; error: boolean } | null>(null)
  const [ticket, setTicket] = useState<Ticket>({ ticket_id: '', customer_id: 'acme-demo', event_id: '', endpoint_id: '', subject: '', description: '' })
  const [attempt, setAttempt] = useState<Attempt>({ attempt_id: '', customer_id: 'acme-demo', event_id: 'evt-invoice-1042', endpoint_id: 'endpoint-billing', sequence: 3, sent_at: new Date().toISOString(), outcome: 'acknowledged', http_status: 200, next_retry_at: null })
  const current = data.cases.find(c => c.id === chosen)
  const visible = data.cases.filter(c => `${c.ticket_id} ${c.subject} ${c.event_id} ${c.finding}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => a.ticket_id === 'T-1042' ? -1 : b.ticket_id === 'T-1042' ? 1 : b.createdAt.localeCompare(a.createdAt))
  const pending = data.cases.filter(c => c.status === 'pending_review').length
  const stale = data.cases.filter(c => c.status === 'pending_review' && !isCurrent(data, c)).length
  useEffect(() => { try { localStorage.setItem(key, JSON.stringify(data)) } catch { /* private storage stays in memory */ } }, [data])
  function action(fn: () => State, success: string) { try { const updated=fn(); setData(updated); const next=updated.cases.find(c=>c.id===chosen); if (next && next.draft!==current?.draft) { setMessage(next.draft); setAck(false) } setNotice({ text: success, error: false }) } catch (e) { setNotice({ text: (e as Error).message, error: true }) } }
  function reset() { const fresh = seedState(); setData(fresh); const first=fresh.cases.find(c => c.ticket_id === 'T-1042')!; setChosen(first.id); setMessage(first.draft); setAck(false); setView('queue'); setPane('evidence'); setNotice({ text: 'Demo reset to three synthetic cases.', error: false }) }
  function addSample() { action(() => addAttempt(data, nextAttempt), 'HTTP 200 recorded. The original case is now stale.') }
  function saveCase() { try { const updated = openCase(data, ticket); const next=updated.cases.find(c=>c.ticket_id===ticket.ticket_id)!; setData(updated); setChosen(next.id); setMessage(next.draft); setAck(false); setView('queue'); setForm(null); setNotice({ text: 'Synthetic case created.', error: false }) } catch (e) { setNotice({ text: (e as Error).message, error: true }) } }
  function saveAttempt() { try { setData(addAttempt(data, attempt)); setForm(null); setNotice({ text: 'Delivery attempt recorded. Related cases may be stale.', error: false }) } catch (e) { setNotice({ text: (e as Error).message, error: true }) } }

  return <div className="min-h-screen bg-[#f6f8f5] text-[#1c3127] lg:flex">
    <aside className="flex shrink-0 flex-col bg-[#10271f] text-[#d8e7dc] lg:min-h-screen lg:w-[246px]">
      <div className="flex items-center gap-2.5 border-b border-white/10 px-6 py-[25px]"><div className="flex size-9 items-center justify-center rounded-xl bg-[#c5ecbe] text-[#174632]"><Activity size={20}/></div><div><div className="text-[19px] font-semibold tracking-[-.045em] text-white">casework<span className="text-[#95d5a2]">.</span></div><div className="text-[10px] font-medium tracking-[.19em] text-[#87a997]">SUPPORT INTELLIGENCE</div></div></div>
      <div className="px-3 pt-6"><div className="px-3 pb-3 text-[10px] font-semibold tracking-[.18em] text-[#82a18e]">WORKSPACE</div><nav className="grid grid-cols-2 gap-1 lg:block">{([['queue', Inbox, 'Case queue'], ['delivery', Activity, 'Delivery log'], ['desk', Send, 'Support desk'], ['guide', BookOpen, 'How it works']] as const).map(([v, Icon, text]) => <button key={v} onClick={() => { setView(v); setNotice(null) }} className={`flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-[13px] lg:mb-1 ${view === v ? 'bg-[#244839] font-semibold text-white' : 'text-[#a9c0ae] hover:bg-white/10 hover:text-white'}`}><Icon size={17}/>{text}{v === 'queue' && <span className="ml-auto rounded bg-[#386e52] px-1.5 text-[10px]">{pending}</span>}</button>)}</nav></div>
      <div className="mt-auto hidden p-4 lg:block"><div className="rounded-xl border border-[#365647] bg-[#1a3729] p-4"><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-[#b6e0bd]"><ShieldCheck size={15}/> PUBLIC SANDBOX</div><p className="text-xs leading-5 text-[#9ab9a5]">Synthetic incidents. Your changes stay in this browser. No customer data or external desk.</p><button onClick={reset} className="mt-4 flex items-center gap-2 text-xs font-semibold text-[#d6eacb]"><RotateCcw size={13}/> Reset demo</button></div></div>
    </aside>
    <main className="min-w-0 flex-1"><div className="border-b border-[#e5ebe5] bg-white px-5 py-3.5 md:px-9"><div className="mx-auto flex max-w-[1430px] items-center justify-between gap-3"><div className="flex items-center gap-2 text-xs text-[#8b9c91]">Workspace <ChevronRight size={12}/><span className="font-semibold text-[#274838]">{view === 'queue' ? 'Case queue' : view === 'delivery' ? 'Delivery log' : view === 'desk' ? 'Support desk' : 'How it works'}</span></div><div className="flex items-center gap-3"><span className="rounded-full bg-[#edf7ef] px-3 py-1.5 text-[11px] font-semibold text-[#27724b]">● LOCAL DEMO</span><a className="hidden items-center gap-1.5 text-xs text-[#567369] hover:text-[#16624c] sm:flex" href="https://github.com/harshdeeply/casework-ai" target="_blank" rel="noreferrer">View source <ExternalLink size={12}/></a></div></div></div>
      <div className="mx-auto max-w-[1430px] px-5 pb-14 pt-9 md:px-9"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 text-[11px] font-bold tracking-[.18em] text-[#3b8d66]">CASEWORK / OPERATOR CONSOLE</div><h1 className="text-[30px] font-semibold tracking-[-.045em] text-[#142d20] md:text-[36px]">{view === 'queue' ? 'Webhook escalations' : view === 'delivery' ? 'Delivery log' : view === 'desk' ? 'Support desk' : 'How the demo works'}</h1><p className="mt-1 text-sm text-[#79867e]">{view === 'queue' ? 'Investigate the evidence. Review the response. Close the loop.' : view === 'delivery' ? 'Scoped attempt records that power each finding.' : view === 'desk' ? 'Approved messages in the isolated demo desk.' : 'A realistic support workflow, with clear production boundaries.'}</p></div><div className="flex gap-2">{view !== 'guide' && <Button variant="outline" size="sm" onClick={() => setForm('attempt')}><Plus/> Add attempt</Button>}{view === 'queue' && <Button size="sm" onClick={() => setForm('case')}><Plus/> New case</Button>}</div></div>
      <div className="mb-6 flex flex-wrap items-center gap-2 rounded-xl border border-[#d9e9dc] bg-[#eff8ee] px-4 py-3 text-xs leading-5 text-[#315b3f]"><ShieldCheck size={17}/><span><b>Public, isolated demo.</b> Incidents are fictional. Changes stay in this browser. No live telemetry, AI API, or external support desk.</span><button className="ml-auto font-semibold underline underline-offset-2" onClick={reset}>Reset</button></div>
      {notice && <div role="status" className={`mb-5 flex justify-between gap-3 rounded-lg border px-4 py-3 text-sm ${notice.error ? 'border-red-200 bg-red-50 text-red-800' : 'border-emerald-200 bg-emerald-50 text-emerald-800'}`}><span>{notice.text}</span><button aria-label="Dismiss" onClick={() => setNotice(null)}><X size={16}/></button></div>}
      {view === 'queue' && <><div className="mb-6 grid gap-3 sm:grid-cols-3"><Metric icon={<Inbox/>} title="OPEN FOR REVIEW" value={pending} note="Synthetic support cases"/><Metric icon={<FileClock/>} title="STALE EVIDENCE" value={stale} note="Refresh before deciding" warm={stale > 0}/><Metric icon={<CheckCheck/>} title="ACKNOWLEDGED" value={data.cases.filter(c => c.finding === 'ACKNOWLEDGED' || c.finding === 'MULTIPLE_ACKS').length} note="Endpoint response only"/></div><div className="grid gap-5 xl:grid-cols-[340px_minmax(0,1fr)]"><Card className="h-fit overflow-hidden"><div className="border-b border-[#edf0ed] px-5 py-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-semibold">Cases <span className="ml-1 text-[#9aa8a0]">{visible.length}</span></h2><Inbox size={15} className="text-[#9aac9e]"/></div><div className="relative"><Search size={15} className="absolute left-3 top-2.5 text-[#96a79c]"/><Input aria-label="Search cases" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search cases or event IDs" className="pl-9"/></div></div><div className="max-h-[790px] overflow-y-auto">{visible.map(c => <button key={c.id} onClick={() => { setChosen(c.id); setMessage(c.draft); setAck(false); setPane('evidence') }} className={`block w-full border-b border-[#eef1ee] px-5 py-4 text-left last:border-0 ${chosen === c.id ? 'bg-[#f0f7f0] shadow-[inset_3px_0_#398965]' : 'hover:bg-[#f8faf8]'}`}><div className="mb-2 flex items-center justify-between"><span className="font-mono text-[11px] text-[#7e9183]">{c.ticket_id}</span><span className={`size-2 rounded-full ${c.status === 'pending_review' ? 'bg-amber-500' : 'bg-emerald-500'}`}/></div><div className="mb-2.5 text-[13px] font-semibold leading-5">{c.subject}</div><div className="flex flex-wrap gap-2"><Badge className={color[c.finding]}>{label[c.finding]}</Badge>{!isCurrent(data,c) && c.status === 'pending_review' && <Badge className="bg-red-50 text-red-700">Stale</Badge>}</div><div className="mt-3 text-[11px] text-[#9aa99e]">{c.event_id} · {status[c.status]}</div></button>)}{!visible.length && <p className="p-6 text-sm text-[#819288]">No matching cases.</p>}</div></Card><div className="min-w-0">{current ? <CasePanel c={current} data={data} pane={pane} setPane={setPane} message={message} setMessage={setMessage} reviewer={reviewer} setReviewer={setReviewer} ack={ack} setAck={setAck} addSample={addSample} refresh={() => action(() => refreshCase(data,current.id),'Evidence refreshed. Review the updated response.')} decide={d => action(() => decideCase(data,current.id,d,reviewer,message,ack), d === 'approve' ? 'Response approved for handoff.' : 'Draft rejected.')} deliver={() => action(() => handoff(data,current.id),'Message delivered to the demo support desk.')} /> : <Card className="p-12 text-sm text-[#819288]">Choose a case to investigate.</Card>}</div></div></>}
      {view === 'delivery' && <Card><CardHeader><CardTitle>Ingested attempts <span className="ml-2 text-sm font-normal text-[#8da197]">{data.attempts.length} records</span></CardTitle></CardHeader><CardContent className="mt-4 overflow-x-auto"><table className="w-full min-w-[730px] text-left text-xs"><thead className="border-b border-[#e8ede8] text-[10px] tracking-[.1em] text-[#8d9e92]"><tr>{['ATTEMPT ID','EVENT / ENDPOINT','SENT AT','OUTCOME','HTTP','NEXT RETRY'].map(h => <th key={h} className="pb-3 pr-4">{h}</th>)}</tr></thead><tbody>{[...data.attempts].sort((a,b)=>b.sent_at.localeCompare(a.sent_at)).map(a => <tr key={a.attempt_id} className="border-b border-[#eef1ed] last:border-0"><td className="py-4 pr-4 font-mono text-[#4a6a58]">{a.attempt_id}</td><td className="py-4 pr-4"><b>{a.event_id}</b><div className="mt-1 text-[#93a098]">{a.endpoint_id}</div></td><td className="py-4 pr-4 whitespace-nowrap">{time(a.sent_at)}</td><td className="py-4 pr-4 capitalize">{a.outcome.replace('_',' ')}</td><td className="py-4 pr-4">{a.http_status ?? '—'}</td><td className="py-4 pr-4 whitespace-nowrap">{a.next_retry_at ? time(a.next_retry_at) : '—'}</td></tr>)}</tbody></table></CardContent></Card>}
      {view === 'desk' && <Card><CardHeader><CardTitle>Demo desk inbox</CardTitle><p className="text-sm text-[#829187]">Only approved handoffs appear here. Repeating a handoff creates no duplicate.</p></CardHeader><CardContent className="mt-5">{data.desk.length ? <div className="space-y-3">{data.desk.map(m => <div key={m.handoffId} className="rounded-xl border border-[#e5ece5] p-5"><div className="mb-3 flex justify-between gap-2"><b>{m.ticketId} <Badge className="ml-2 bg-emerald-50 text-emerald-700">Delivered</Badge></b><span className="text-xs text-[#95a69b]">{time(m.at)}</span></div><p className="text-sm leading-6 text-[#516258]">{m.message}</p><div className="mt-3 font-mono text-[10px] text-[#9aa99f]">Idempotency key: {m.handoffId}</div></div>)}</div> : <div className="py-20 text-center"><Inbox size={29} className="mx-auto mb-4 text-emerald-600"/><h3 className="font-semibold">No handoffs yet</h3><p className="mt-1 text-sm text-[#899b8e]">Approve a case, then send it from the queue.</p><Button variant="outline" className="mt-5" onClick={() => setView('queue')}>Review cases <ArrowRight/></Button></div>}</CardContent></Card>}
      {view === 'guide' && <div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>The incident</CardTitle></CardHeader><CardContent className="pt-4 text-sm leading-7 text-[#586a5e]">A customer says their billing webhook never arrived. A delivery timed out; the second returned HTTP 503. A scheduled retry has passed, but no later result appears in the current log. Can support safely say what happened?<div className="mt-5"><Button onClick={() => { setView('queue'); setChosen(data.cases.find(c=>c.ticket_id==='T-1042')?.id||'') }}>Investigate <ArrowRight/></Button></div></CardContent></Card><Card><CardHeader><CardTitle>Try the workflow</CardTitle></CardHeader><CardContent className="space-y-3 pt-4 text-sm text-[#596c5f]">{['Read the delivery evidence and runbook citation.','Add the sample HTTP 200 to make the draft stale.','Try review; the stale evidence check blocks it.','Refresh, edit, approve, and hand off.','See the result in the demo support desk.'].map((step,i)=><div className="flex gap-3" key={step}><span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-emerald-50 text-xs font-bold text-emerald-700">{i+1}</span>{step}</div>)}</CardContent></Card><Card className="lg:col-span-2"><CardContent className="flex flex-wrap justify-between gap-4 pt-6"><div><h3 className="font-semibold">Production boundaries</h3><p className="mt-1 max-w-2xl text-sm leading-6 text-[#728477]">The public UI runs locally in each visitor's browser. The repository contains a separate Python + SQLite reference backend and its tests. There is no production identity layer, shared database, external helpdesk, or measured customer outcome.</p></div><a href="https://github.com/harshdeeply/casework-ai" target="_blank" rel="noreferrer"><Button variant="outline">Explore source <ExternalLink/></Button></a></CardContent></Card></div>}
      <footer className="mt-10 flex flex-wrap justify-between gap-3 border-t border-[#e5eae4] pt-5 text-[11px] text-[#9aa99d]"><span>CASEWORK · EVIDENCE-BOUND OPERATIONS</span><span>Sample data · Browser-local state · No external messages</span></footer></div></main>
    {form && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#10271f]/55 px-4 py-8" onMouseDown={e => { if (e.target===e.currentTarget) setForm(null) }}><div role="dialog" aria-modal="true" aria-label={form === 'case' ? 'Open case' : 'Add attempt'} className="max-h-full w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex justify-between"><div><h2 className="text-xl font-semibold">{form === 'case' ? 'Open a case' : 'Add a delivery attempt'}</h2><p className="mt-1 text-xs text-[#8b9b90]">Fictional data only · This browser session</p></div><button aria-label="Close form" onClick={() => setForm(null)}><X size={18}/></button></div>{form === 'case' ? <div className="space-y-3">{(['ticket_id','customer_id','event_id','endpoint_id','subject','description'] as const).map(k => <label key={k} className="block text-xs font-semibold capitalize text-[#5e7163]">{k.replace('_',' ')}{k === 'description' ? <Textarea className="mt-1" value={ticket[k]} onChange={e => setTicket({...ticket,[k]:e.target.value})}/> : <Input className="mt-1" value={ticket[k]} onChange={e => setTicket({...ticket,[k]:e.target.value})}/>}</label>)}<Button className="mt-3 w-full" onClick={saveCase}>Open case</Button></div> : <div className="space-y-3">{(['attempt_id','customer_id','event_id','endpoint_id','sequence','sent_at'] as const).map(k => <label key={k} className="block text-xs font-semibold capitalize text-[#5e7163]">{k.replaceAll('_',' ')}<Input className="mt-1" type={k==='sequence'?'number':'text'} value={attempt[k]} onChange={e => setAttempt({...attempt,[k]:k==='sequence'?Number(e.target.value):e.target.value})}/></label>)}<label className="block text-xs font-semibold">Outcome<select className="mt-1 h-10 w-full rounded-lg border border-[#dfe6e0] bg-white px-3" value={attempt.outcome} onChange={e => { const outcome=e.target.value as Attempt['outcome']; setAttempt({...attempt,outcome,http_status:outcome==='acknowledged'?200:outcome==='http_error'?503:null,next_retry_at:null}) }}><option value="acknowledged">Acknowledged</option><option value="http_error">HTTP error</option><option value="timeout">Timeout</option></select></label>{attempt.outcome !== 'timeout' && <label className="block text-xs font-semibold">HTTP status<Input className="mt-1" type="number" value={attempt.http_status??''} onChange={e => setAttempt({...attempt,http_status:Number(e.target.value)})}/></label>}{attempt.outcome !== 'acknowledged' && <label className="block text-xs font-semibold">Next retry at (optional ISO timestamp)<Input className="mt-1" value={attempt.next_retry_at??''} onChange={e => setAttempt({...attempt,next_retry_at:e.target.value||null})}/></label>}<Button className="mt-3 w-full" onClick={saveAttempt}>Add attempt</Button></div>}</div></div>}
  </div>
}

function Metric({ icon, title, value, note, warm=false }: { icon: React.ReactNode; title: string; value: number; note: string; warm?: boolean }) { return <Card className="flex items-start justify-between px-5 py-5"><div><div className="text-[10px] font-bold tracking-[.14em] text-[#8fa194]">{title}</div><div className="mt-2 text-[29px] font-semibold leading-8 tracking-[-.05em]">{String(value).padStart(2,'0')}</div><div className="mt-1.5 text-[11px] text-[#a0afa4]">{note}</div></div><div className={`rounded-xl p-2.5 [&_svg]:size-[18px] ${warm?'bg-amber-50 text-amber-600':'bg-emerald-50 text-emerald-600'}`}>{icon}</div></Card> }

function CasePanel({ c, data, pane, setPane, message, setMessage, reviewer, setReviewer, ack, setAck, addSample, refresh, decide, deliver }: { c: Case; data: State; pane: Pane; setPane: (v:Pane)=>void; message:string; setMessage:(v:string)=>void; reviewer:string; setReviewer:(v:string)=>void; ack:boolean; setAck:(v:boolean)=>void; addSample:()=>void; refresh:()=>void; decide:(v:'approve'|'reject')=>void; deliver:()=>void }) {
  const current = isCurrent(data,c), live = scopedAttempts(data,c), book=runbookFor(c.finding)
  return <Card className="overflow-hidden"><div className="border-b border-[#e8ede8] px-6 py-6 md:px-7"><div className="mb-3 flex flex-wrap items-center gap-2"><span className="font-mono text-[11px] font-semibold text-[#549169]">{c.ticket_id}</span><span className="text-[#bec9bf]">/</span><span className="text-[11px] text-[#94a496]">{c.customer_id} · {c.endpoint_id}</span><Badge className="ml-auto bg-[#edf2ed] text-[#698071]">{status[c.status]}</Badge></div><h2 className="text-[23px] font-semibold tracking-[-.04em]">{c.subject}</h2><p className="mt-2 text-[13px] leading-6 text-[#77897a]">{c.description}</p><div className="mt-4 flex flex-wrap gap-2"><Badge className={color[c.finding]}>{label[c.finding]}</Badge><Badge className="bg-[#f0f4ef] text-[#627b69]">{c.evidenceSnapshot.length} attempts cited</Badge>{!current && <Badge className="bg-amber-50 text-amber-800">Evidence changed</Badge>}</div></div>
    {!current && <div className="mx-6 mt-5 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900 md:mx-7"><span className="flex items-center gap-2"><FileClock size={17}/> New delivery evidence arrived. Current logs indicate <b>{label[findingFor(live)]}</b>.</span>{c.status==='pending_review' && <Button variant="outline" size="sm" onClick={refresh}><RefreshCcw/> Refresh evidence</Button>}</div>}
    <div className="flex gap-6 border-b border-[#e8ede8] px-6 pt-4 md:px-7">{([['evidence','Evidence'],['draft','Review draft'],['activity','Audit trail']] as const).map(([v,t])=><button key={v} onClick={()=>setPane(v)} className={`border-b-2 pb-3 text-xs font-semibold ${pane===v?'border-emerald-700 text-emerald-800':'border-transparent text-[#91a094]'}`}>{t}</button>)}</div>
    {pane==='evidence' && <div className="space-y-5 p-6 md:p-7"><div><h3 className="text-sm font-semibold">Delivery timeline</h3><p className="mt-1 text-xs text-[#8a9c8e]">Pinned snapshot · event <code>{c.event_id}</code></p></div>{c.evidenceSnapshot.length ? <div className="pl-3">{c.evidenceSnapshot.map((a,i)=><div key={a.attempt_id} className="relative border-l border-[#dce8df] pb-6 pl-7 last:border-transparent last:pb-0"><span className={`absolute -left-[7px] top-1 size-3.5 rounded-full border-[3px] border-white ${a.outcome==='acknowledged'?'bg-emerald-500':'bg-amber-500'}`}/><div className="flex flex-wrap justify-between gap-2"><b className="text-xs">Attempt {i+1} <code className="ml-1 text-[10px] font-normal text-[#a1afa5]">{a.attempt_id}</code></b><span className="text-[11px] text-[#8da092]">{time(a.sent_at)}</span></div><div className="mt-2 flex flex-wrap items-center gap-2 text-xs"><Badge className={a.outcome==='acknowledged'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-800'}>{a.outcome==='timeout'?'Connection timeout':'HTTP '+a.http_status}</Badge>{a.next_retry_at && <span className="flex items-center gap-1 text-[#85978a]"><Clock3 size={12}/> Retry scheduled {time(a.next_retry_at)}</span>}</div></div>)}</div> : <div className="rounded-lg bg-[#f6f8f5] p-5 text-sm text-[#829486]">No matching attempt in the available delivery log.</div>}{!current && <div className="rounded-lg border border-dashed border-amber-300 bg-amber-50 p-4 text-xs text-amber-900">{live.length-c.evidenceSnapshot.length} new attempt(s) in the current log. Refresh to cite them.</div>}{c.ticket_id==='T-1042' && c.status==='pending_review' && !data.attempts.some(a=>a.attempt_id===nextAttempt.attempt_id) && <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#dce9dc] bg-[#f3f8f1] p-4"><div><b className="text-xs">Simulate the next delivery</b><p className="mt-1 text-[11px] text-[#849889]">Record the sample HTTP 200 and invalidate the old draft.</p></div><Button size="sm" variant="secondary" onClick={addSample}>Add HTTP 200 <ArrowRight/></Button></div>}<div className="border-t border-[#edf0ed] pt-5"><div className="mb-3 flex items-center gap-2 text-xs font-semibold"><BookOpen size={16} className="text-emerald-700"/> Runbook citation <code className="ml-auto text-[10px] text-[#8aa18e]">{book.id}</code></div><div className="rounded-xl bg-[#f6f8f5] p-4"><b className="text-xs">{book.title}</b><p className="mt-2 text-xs leading-6 text-[#708274]">{book.text}</p></div></div><div className="text-[10px] text-[#a3b0a5]">Runbook version: 2026-09-example-v2 · {c.evidenceIds.join(', ')}</div></div>}
    {pane==='draft' && <div className="space-y-5 p-6 md:p-7"><div><h3 className="text-sm font-semibold">Customer-facing response</h3><p className="mt-1 text-xs text-[#8fa092]">Grounded template · Edit before handoff</p></div><Textarea aria-label="Customer-facing response" value={c.status==='pending_review'?message:c.finalMessage||c.draft} disabled={c.status!=='pending_review'} onChange={e=>setMessage(e.target.value)} className="min-h-[170px]"/><div className="flex flex-wrap items-center gap-2 text-[11px] text-[#869b8b]"><Link2 size={13}/> Citations {c.evidenceIds.map(i=><code className="rounded bg-[#f0f5ef] px-2 py-1 text-[#487452]" key={i}>{i}</code>)}</div><div className="rounded-xl border border-[#e5ece5] bg-[#f8faf7] p-4"><div className="mb-3 flex items-center gap-2 text-xs font-semibold"><ShieldCheck size={16} className="text-emerald-700"/> Reviewer controls</div>{c.status==='pending_review'?<><label className="block text-xs font-medium text-[#758877]">Reviewer name<Input className="mt-1.5" aria-label="Reviewer name" value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label>{uncertain(c.finding) && <label className="mt-4 flex items-start gap-2.5 text-xs leading-5 text-[#5b705e]"><input type="checkbox" className="mt-1 accent-emerald-700" checked={ack} onChange={e=>setAck(e.target.checked)}/>I checked the uncertain evidence and the wording does not overstate what the logs prove.</label>}<div className="mt-5 flex flex-wrap gap-2"><Button size="sm" disabled={!current} onClick={()=>decide('approve')}><Check/> Approve response</Button><Button size="sm" variant="outline" disabled={!current} onClick={()=>decide('reject')}><X/> Reject draft</Button></div>{!current && <p className="mt-3 text-xs text-amber-800">Refresh the evidence before deciding.</p>}</>:<p className="text-xs text-[#657968]">{c.status==='rejected'?'Rejected. Nothing was handed off.':`Reviewed by ${c.reviewer}.`}</p>}</div>{c.status==='approved' && <Button onClick={deliver}><Send/> Send to demo support desk</Button>}{c.status==='handed_off' && <div className="flex items-center gap-2 rounded-xl bg-emerald-50 p-4 text-xs font-semibold text-emerald-800"><CheckCheck size={17}/> Delivered · idempotency key {c.id}</div>}</div>}
    {pane==='activity' && <div className="p-6 md:p-7"><h3 className="mb-5 text-sm font-semibold">Case activity</h3>{[...c.audit].reverse().map((a,i)=><div key={i} className="flex gap-4 border-l border-[#dfebe0] pb-6 pl-5 last:border-transparent"><div className="-ml-[27px] mt-0.5 size-3.5 shrink-0 rounded-full border-[3px] border-white bg-emerald-600"/><div><b className="text-xs capitalize">{a.action.replaceAll('_',' ')}</b><p className="mt-1 text-[11px] text-[#91a297]">{a.actor} · {time(a.at)}</p>{a.detail && <p className="mt-1 text-[11px] text-[#76917a]">Finding: {a.detail}</p>}</div></div>)}<p className="rounded-lg bg-[#f7f9f7] p-4 text-xs leading-5 text-[#8a9a8d]">Workflow actions are recorded locally. No message is sent to an external service.</p></div>}
  </Card>
}
